### ISSUE TITLE
objects generated via the map seem to differ from objects placed by the mouse

### ISSUE THREAD

**Issue by dantaeyoung** [frnsys/pathfinding#13]
Generating a 'food'-tagged object via the input layout doesn't attract HungryGhosts..  It seems to be because this.adjacentCoords isn't working, which is because World.parseObjects() stores coordinates differently than how mouse-placed objects store coordinates

**Comment by frnsys** [comment]
whoops, was returning coords as arrays, e.g. `[0,0]`, instead of as objects, e.g. `{x: 0, y: 0}`. thanks!
